#!/bin/bash

# ============================================
# AEGIS Autonomous Git Sync
# Automatically commits and pushes changes
# while keeping secrets encrypted
# ============================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRANCH="${GIT_BRANCH:-main}"
SYNC_INTERVAL="${SYNC_INTERVAL:-300}"  # 5 minutes default

echo -e "${BLUE}============================================${NC}"
echo -e "${BLUE}🔥 AEGIS Autonomous Git Sync${NC}"
echo -e "${BLUE}============================================${NC}"
echo ""

cd "$REPO_DIR"

# Check if git repo
if [ ! -d ".git" ]; then
    echo -e "${RED}❌ Not a git repository${NC}"
    exit 1
fi

# Function to encrypt secrets before commit
encrypt_secrets() {
    echo -e "${YELLOW}🔒 Encrypting secrets...${NC}"

    if [ -f ".env" ] && [ -n "$AEGIS_MASTER_PASSWORD" ]; then
        python3 tools/secrets_manager.py encrypt-env
        git add .env.encrypted
        echo -e "${GREEN}✓ Secrets encrypted${NC}"
    else
        if [ ! -f ".env" ]; then
            echo -e "${YELLOW}⚠️  No .env file found${NC}"
        fi
        if [ -z "$AEGIS_MASTER_PASSWORD" ]; then
            echo -e "${YELLOW}⚠️  AEGIS_MASTER_PASSWORD not set, skipping encryption${NC}"
        fi
    fi
}

# Function to check for changes
has_changes() {
    git diff --quiet && git diff --staged --quiet
    return $?
}

# Function to auto-commit and push
auto_sync() {
    echo -e "${BLUE}📊 Checking for changes...${NC}"

    # Check if there are changes
    if has_changes; then
        echo -e "${YELLOW}📝 Changes detected${NC}"

        # Encrypt secrets first
        encrypt_secrets

        # Add all files (respecting .gitignore)
        git add -A

        # Generate commit message
        TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
        COMMIT_MSG="🤖 Auto-sync: ${TIMESTAMP}

Auto-committed changes:
$(git status --short | head -10)

🔥 Generated by AEGIS Autonomous Sync"

        # Commit
        echo -e "${GREEN}💾 Committing changes...${NC}"
        git commit -m "$COMMIT_MSG"

        # Push
        echo -e "${GREEN}⬆️  Pushing to GitHub...${NC}"
        if git push origin "$BRANCH"; then
            echo -e "${GREEN}✓ Successfully pushed to GitHub${NC}"
        else
            echo -e "${RED}❌ Push failed${NC}"
            return 1
        fi
    else
        echo -e "${BLUE}✓ No changes to sync${NC}"
    fi
}

# Function to run continuous sync
continuous_sync() {
    echo -e "${GREEN}🔄 Starting continuous sync (every ${SYNC_INTERVAL}s)${NC}"
    echo -e "${YELLOW}Press CTRL+C to stop${NC}"
    echo ""

    while true; do
        auto_sync
        echo ""
        echo -e "${BLUE}⏰ Next sync in ${SYNC_INTERVAL}s...${NC}"
        sleep "$SYNC_INTERVAL"
    done
}

# Main
case "${1:-once}" in
    once)
        auto_sync
        ;;
    continuous)
        continuous_sync
        ;;
    watch)
        continuous_sync
        ;;
    *)
        echo "Usage: $0 [once|continuous|watch]"
        echo ""
        echo "  once       - Sync once and exit (default)"
        echo "  continuous - Keep syncing every ${SYNC_INTERVAL}s"
        echo "  watch      - Alias for continuous"
        exit 1
        ;;
esac
